### ISSUE TITLE
Mõelda, kas concepts võiks panna local DB'sse

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#101]
Siiani on nii, et kõik viitamised config.json failis on 'slug' baasil tehtud. See töötab, aga kui tahta viidata välisele concept'ile siis on keeruline leida millisest repost see peaks tulema. Täna on ainuke viis läbi vaadata kõik kursused ja otsida sealt õige concept
Kui concept osa oleks DB's, siis oleks õige tüki leidmine väga lihtne ja kiire. Aga tekib uus probleem - kuidas tagada DB ja git'i sünkro?
Üks lahendus võiks olla cron skript, mis iga x aja tagant võrdleb git'i ja DB'd (ilmselt git on siin tõe allikas)
Kursuse muutmisel toimuks loomulikult DB uuendamine automaatselt.
DB's peaks hoidma kursuste kõikide harude konfe (master - et õpilase vaade töötaks, draft - et töötaks muutmine, arhiivid - et saaks ajalugu vaadata)

**Comment by mrtrvl** [comment]
Kas ei oleks mõeldav `slug`-i asemel kasutada näiteks otseviidet `concept`-ile?

**Comment by mrtrvl** [comment]
Iseenesest ma arvan, et andmebaas on OK.

**Comment by kaiusk** [comment]
Lisada loengu components juurde ka repo nimi
