### ISSUE TITLE
uurida, miks on about.md ja mitte readme.md

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#13]

**Comment by kaiusk** [comment]
vahetasin koodis kõik viited about.md -> readme.md ja samuti muutsin test repos kõik about.md failid ümber readme.md'ks

tehtud muudatused: 14f267b8651cb817466e27dc1c71ac29fb176321

**Comment by mrtrvl** [comment]
Kas leidsid ka kusagilt mingi põhjenduse või said aru, miks oli kasutatud just `about.md`?

**Comment by mrtrvl** [comment]
Uuri seda ka, kas kasutada `readme.md` või `README.md` nime - esimese emotsiooni pealt tundub, et Githubis kasutatakse pigem suurte tähtedega formaati. Miks see nii on ja kas on mõistlik kasutada selle asemel väikeste tähtedega formaati?

**Comment by kaiusk** [comment]
Tegelikult jõudsin ise ka selleni. Tundub, et README on õigem: https://www.makeareadme.com/
Ma teen selle kohta eraldi issue.

Ja miks about ja README - siis minu arvates selle pärast, et readme failides olid juhised kasutajale...
