### ISSUE TITLE
Panna Martti kontaktid samuti .env faili

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#22]
Hetkel on "võta ühendust" kontaktid otse html's, aga võiks tulla näiteks .env failist

**Comment by siiriinno** [comment]
Martti kontaktid .env failis 56d2ddac43950a7a724e54ee8d1315602f0fda86

**Comment by mrtrvl** [comment]
Kas siin on tegemist projekti juurkaustas oleva `.ENV` failiga? Sellisel juhul tehke vastavad muudatused kohe ka https://github.com/TLUHK-RIF21/HK-Ainekursus/blob/main/.env.example faili.

Sama kehtib https://github.com/TLUHK-RIF21/HK-Ainekursus/issues/18 kohta.
