### ISSUE TITLE
kursuse lisamise lo-fi prototüüp

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#23]
Kasutaja peab sisestama:
- kursuse nime
- kursuse ÕIS'i lingi
- kursuse kirjelduse (pikem tekst)
- (võimalik ka uue readme.md loomine kurususe jaoks....)

**Comment by siiriinno** [comment]
![Image](https://github.com/TLUHK-RIF21/HK-Ainekursus/assets/102409893/a2af5ea4-f982-4cbe-af34-1c8fcce252fb)
