### ISSUE TITLE
Kooskõlastus kliendiga 

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#30]
Küsin üle, kas oleme õigel teel ja selline lahendus sobib:
1. kursuse lisamine template järgi. Siin plaanisime lisada lingi põhimenüüsse. Sealt avaneks uus leht, kus kasutaja peab sisestama kursuse nime ja ÕIS lingi. Lisaks võib lisada lühema kirjelduse (mis läheb config.json) ja pikema kirjelduse (mis läheb README'sse). Nende andmetega luuakse kursus ja kasutaja suunatakse kursuse ülevaatesse. 
2. Uue haru lisamine. Kursuse ülevaate lehel on paremas menüüs (seal kus täna näidatakse kõiki harusid) valik, kus on näha kõikide lisatavate harude nimed (tiimide nimed, miinus need tiimid, millele juba on haru loodud). Ja lisaks ka nupp "Lisa". Kasutaja peaks veel määrama semestri ja õppejõu - kuidas neid küsida on veel lahtine (mõtlesin pop-upi peale). Jällegi, peale edukat haru lisamist, suunatakse kasutaja tagasi ülevaate lehele.
3. Kursuse muutmine. See on kõige keerukam. Mõtlesime teha nii, et muuta saaks sektsioonide kaupa kuna sektsioonid on ülesehituselt väga sarnased. Eraldi saaks muuta config.json osa. Kasutaja saab muuta iga faili sisu, lisada või kustutada faile. 

Kui see loogika sobib, teema paber prototüübid ja testimine kasutajate peal.

**Comment by mrtrvl** [comment]
Rääkisime telefoni teel sellest, kuidas peaks välja nägema uue õppematerjali loomine/muutmine:
- koosneb väiksematest eraldiseisvatest tükikestest
- neid tükikesi saab lisada erinevatesse materjalidesse
- kui muudad ühte tükikest, muutub ka mujal
- peaks olema ülevaade sellest, millised materjalid seda tükikest kasutavad
- ...

Lisaks arutasime kasutajate haldust - ehk ei ole praegune teamide kaupa manageerimine kõige parem?
- osa õppeainetest on valikained ja kõik kursusel olevad õpilased ei pea materjale nägema (ei taha?)
- osades ainetes võib olla õpilasi varasematelt/järgmistelt kursustelt (tesitest organisatsioonidest)
- ...

Kasutajate halduse suhtes oleks mõistlik teha koostööd Githubi tööriista arendajatega ja ka tunniplaani arendajatega.

**Comment by mrtrvl** [comment]
Võibolla oli midagi veel, hetkel ei tulnud rohkem meelde ...
