### ISSUE TITLE
Uue kursuse nimetus ÕIS'st?

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#41]
Kasutajatega testides tuli selline mõte - äkki piisab kursuse loomiseks ainult ÕIS'i lingist?

ÕIS'st tuleks automaatselt nimetus ja kirjeldus ehk README.md. Peale kursuse lisamist suunatakse kasutaja andmete muutmise lehele, kus saab muuta nii nimetust kui ka kirjeldust. 
Väike probleem võib tekkida repo nimega, mis peab olema unikaalne, aga selle saaks lahendada mingi liite lisamisega nimele - repo nime kasutajad ei näe - neile on oluline nimi, mis salvestatud config.json faili.

Kas selline lahendus võik sobida?

**Comment by mrtrvl** [comment]
Mmm. Miks ka mitte, kui kasutaja saab pärast seal asju muuta.

Sobib, katsetage.
