### ISSUE TITLE
Sisuteemade linkimine

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#42]
Teine asi, mis testides välja tuli, puudutab sisuteemade taaskasutust ehk linkimist. 
Mõlemad testitavad arvasid, et sellist lahendust oleks väga vaja, aga mõlemad tõid ka välja selle, et teemade jagamist peab saama autor kontrollida. 
Ehk et autor otsustab kellele tema poolt lisatud teema on nähtav (vaikimisi teised õppejõud teiste loodud teemasid ei näe). 
Ideaalis võiks teemade jagamine olla kolme tasandiline: a) ei jaga üldse; b) jagan nn read-only; c) jagan nii, et teised saavad muuta.

Küsimus - kas selline asi võiks tulla teemaks ja kas mahub skoopi?

PS. Siin hakkab mulle tunduma, et vist oleks vaja lisaks git'le andmeid hoida ka päris DB's - ma mõtlen just config.json osa kolimist DB'sse. Sest kui mõelda sisuteemade jagamisele ja ka kasutajate õigustele, siis oleks selliseid seoseid palju lihtsam hoida DB's.

**Comment by mrtrvl** [comment]
Tundub hea mõte olevat. Ma küll arvan, et õppematerjalide puhul võiks olla hea tava see, et kõik on avalik, kuid kõik ei pruugi seda arvata. Üks variant on siduda seda litsentsidega - neid peaks mingi hetk hakkama niikuinii rakendama, kuid esialgu võib seda ka muudmoodi teha (samas võiks seda kaaluda).
Mulle tundub, et andmebaas võib olla lõpuks nii ehk naa möödapääsmatu, osade asjade vägisi rakendamine gitiga võib teha asja lihtsalt keerulisemaks. Mõistlikkuse piires võiks kasutada nii palju kui võimalik, git-i, kuid ei maksa sellega äärmustesse minna.
