### ISSUE TITLE
Ühine andmebaas

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#43]
Oleks vaja luua ühiselt ligipääsetav andmebaas, mida hakkaks kasutama meie grupp ja ka GitHubTööriista grupp ( @kloopman ja @RenatRank )

**Comment by mrtrvl** [comment]
Kas see teema on veel ajakohane?

**Comment by RenatRank** [comment]
Ma arvan, et aegunud.

**Comment by kaiusk** [comment]
Nõus. Teema suletud
