### ISSUE TITLE
Küsida Mihkli käest live/test server

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#50]
Selleks, et rakendust paremini demoda ja testida oleks vaja seda hostida kusagil (tigu või ainekursus.hk.tlu.ee)

**Comment by kaiusk** [comment]
Repo readme.md on kirjas, et rakendus asub aadressil: http://ainekursus.hk.tlu.ee/ aga reaalselt seal midagi ei ole.
Oleks vaja sinna ligipääsu, et saaks testiks rakenduse sinna üles panna...

**Comment by mihkelpulst** [comment]
Tegin teile  @kaiusk ja @siiriinno ligipääsud ainekursus.hk.tlu.ee serverile ja saatsin sisselogimise info TLÜ emailile.
