### ISSUE TITLE
Täiendada http://users.hk.tlu.ee:3333/groups apit

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#51]
Lisaks olemasolevatele andmetele oleks vaja lisada juurde ainekood, EAP'de arv, arvestus/eksam ja semester.
Tagastatav objekt võiks olla midagi sellist:
```
{
      "id": 1,
      "name": "Programmeerimine III 2023",
      "repository": "https://github.com/tluhk/Programmeerimine_III",
      "code": "HKI5076.HK",
      "credits": 4,
      "form": "arvestus",
      "semester": "S2023",
      "users": [],
      "teachers": []
}
```

**Comment by mrtrvl** [comment]
Lisatud vastavad väljad andmebaasi struktuuri ja täiendatud rakenduse komponente vastavalt: [7b4c9dc78234a71bb313dca706cd5f6b57d3ccff](https://github.com/tluhk/HK-Users-Service/commit/7b4c9dc78234a71bb313dca706cd5f6b57d3ccff)
