### ISSUE TITLE
Lisada POST http://users.hk.tlu.ee:3333/groups endpoint

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#52]
Lisada http://users.hk.tlu.ee:3333/groups api'le võimalus lisada uus grupp/kursus. 
Meie rakendus saadaks uue kursuse õnnestunud lisamisel POST päringu. Päringu sisuks oleks sama JSON struktuur mis GET päringul: "users" oleks tühi array ja "teachers" sisuks oleks see kasutaja, kes kursuse lisas, "id" võime panna "null" (või üldse ära jäta). 
Vastuseks ootame status=201 (piisab staatuse koodist) või vea korral  vea teksti.

Meie rakendus saaks teha esmase valideerimise - st kontrolliks, et sama repo_url'ga pole kursust juba lisatud

**Comment by mrtrvl** [comment]
Lisatud `POST /groups` endpoint koos lisamise funktsionaalsusega. https://github.com/tluhk/HK-Users-Service/commit/17322d16e7c57432b1999626c4a85ad390fcb400
Hetkel on ainuke nõutud väli `name`, kuna võib juhtuda, et on vaja moodustada ka gruppe, mis ei ole otseselt õppeaine muude parameetritega seotud (rühmatööde jaoks näiteks).
Vastuvõetavad parameetrid on:
- Grupi nimi `name`: string - nõutud
- Repositoorium `repository`: string - valikuline
- Ainekood `code`: string - valikuline
- Aine maht EAP-des `credits`: number - valikuline
- Hindamisvorm `form`: string - valikuline
- Semester `semester`: string - valikuline

Eduka lisamise puhul tagastatakse staatus `201` ja vastus koos loodud grupi objektiga.
Näiteks: 
```json
{
  "success": true,
  "message": "Group created",
  "data": {
    "id": 6,
    "name": "Testgrupp",
    "repository": null,
    "code": null,
    "credits": null,
    "form": null,
    "semester": null,
    "users": null,
    "teachers": null
  }
}
```

Kui lisamisel tekib mingi probleem, siis tagastatakse vastava koodi ja sisuga vastuse objekt.
