### ISSUE TITLE
puuduva config.json loomine

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#69]
Selline idee - kuna kursused tulevad kõik uue api kaudu, siis meie rakendus võiks vajadusel ise luua puuduva config.json faili.
Juhul kui repo struktuur vastab min. nõuetele (on olemas lessons, concepts, ... kaustad koos README-md failidega), siis rakendus lisab puuduva config.json faili

**Comment by mrtrvl** [comment]
Jah, miks mitte. Kui juba need kaustad olemas on, siis ilmselt on tegemist ikkagi juba loodava kursusega, mis võiks selle rakenduse kaudu käiku minna.

**Comment by kaiusk** [comment]
võtame töösse
