### ISSUE TITLE
Mida teha, kui kasutajal on nii õpetaja kui ka õpilase roll?

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#70]
Hetkel on nii, et kasutaja saab olla kas õpilane või õpetaja, aga uus api lubab teoorias mõlemat rolli.

**Comment by mrtrvl** [comment]
Tavaliselt on sellisel juhul kusagil mingi nupp kasutajal, millega ta saab valida, millises rollis ta parasjagu on.
Moodles on nii näiteks:
![image](https://github.com/TLUHK-RIF21/HK-Ainekursus/assets/26817366/11e3efd6-d834-44e4-a12c-16bcd295d58a)

Kas midagi sarnast on võimalik teha?
