### ISSUE TITLE
ainekursus.hk.tlu.ee serverisse mysql ligipääs

### ISSUE THREAD

**Issue by kaiusk** [TLUHK-RIF21/HK-Ainekursus#80]
oleks vaja kasutajat ja parooli, millega saaks ligig ainekursuse serveris jooksvale mariadb'le

**Comment by mihkelpulst** [comment]
Krister kunagi installis ainekursuse VM'i MariaDB SQL serveri, aga seda ta ei kasutanud vaid jooksutas Docker'is MariaDB serverit "haapsalu-mariadb". VM'is olev MariaDB tuleks eemaldada, sest see võib Docker'is olevad MariaDB'd segada, kuna hõivab sama pordi!

**Lisaks teie kasutajatel on sudo, mis tähendab, et te saate teha kõike, mida root teeb!**

/home/krister.sepp/HK-Ainekursus/.env failis on paroolid, aga neid ei peaks teil vaja minema.

Siin on kirjas kuidas algselt oli docker ja andmebaas seadistatud:
[https://github.com/TLUHK-RIF21/HK-Ainekursus/blob/main/README_vana.md](https://github.com/TLUHK-RIF21/HK-Ainekursus/blob/main/README_vana.md)

Siin on Docker'i automaat setup, mida Krister kasutas:
[https://github.com/TLUHK-RIF21/HK-Ainekursus/blob/main/setup-docker.sh](https://github.com/TLUHK-RIF21/HK-Ainekursus/blob/main/setup-docker.sh)
**NB:** See skript ei ole perfektne ja võib probleeme tekitada.

**Comment by kaiusk** [comment]
Tänud!
